# Generated by Django 3.2.12 on 2024-02-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0007_remove_participant_pass_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='user_interest',
        ),
    ]
