export const eventMap={
    "Script Writing Workshop" : "video_making_workshop",
    "Comic Writing Workshop" : "creative_writing_workshop",
    "Nautanki Saala" : "acting_workshop",
    "Verse Come Verse Serve" : "prompt_poetry",
    "Noob Quiz" : "noob_quiz",
    "Are Your Words-Worth?" : "word_games",
    "Clueminati" : "treasure_hunt",
    "Just A Minute Speech" : "just_a_minute_speech",
    "Hindi Debate" : "hindi_debate",
    "English Debate" : "english_debate",
    "What If They Met" : "character_reenactment",
    "Mythology quiz" : "mythology_quiz",
    "Let's Get Quizzical" : "mela_quiz",
    "Open Mic" : "open_mic",
}